import { TeamCard, OpenPosition, TeamApplication } from '@/types/platform';

// Mock Team Cards for development
export const mockTeamCards: TeamCard[] = [
  {
    id: '1',
    name: 'EcoTrack',
    slug: 'ecotrack',
    description: 'Building a comprehensive carbon footprint tracking app for individuals and businesses to monitor and reduce their environmental impact.',
    projectGoals: 'Launch MVP within 6 months, onboard 10,000 users in first year, and partner with 50+ businesses for corporate sustainability programs.',
    industry: 'Climate Tech',
    stage: 'mvp',
    founderId: 'user1',
    founderName: 'Sarah Chen',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    members: [
      {
        id: 'tm1',
        startupId: '1',
        userId: 'user1',
        name: 'Sarah Chen',
        role: 'Founder',
        title: 'CEO & Co-Founder',
        bio: 'Former product manager at Google, passionate about sustainability',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        isFounder: true,
        createdAt: '2024-01-15T00:00:00Z',
      },
      {
        id: 'tm2',
        startupId: '1',
        userId: 'user2',
        name: 'Alex Kumar',
        role: 'Technical Lead',
        title: 'CTO',
        bio: 'Full-stack developer with 8 years experience',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        isFounder: false,
        createdAt: '2024-02-01T00:00:00Z',
      },
    ],
    openPositions: [
      {
        id: 'pos1',
        teamCardId: '1',
        title: 'UI/UX Designer',
        role: 'Designer',
        description: 'Looking for a creative designer to help shape our user experience and visual identity.',
        requiredSkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
        experienceLevel: 'mid',
        commitment: 'part-time',
        equityOffered: '1-2%',
        status: 'open',
        applications: [],
        createdAt: '2024-11-01T00:00:00Z',
      },
      {
        id: 'pos2',
        teamCardId: '1',
        title: 'Marketing Lead',
        role: 'Marketing',
        description: 'Drive growth and brand awareness for our sustainability platform.',
        requiredSkills: ['Digital Marketing', 'Content Strategy', 'Social Media', 'Growth Hacking'],
        experienceLevel: 'mid',
        commitment: 'full-time',
        equityOffered: '2-3%',
        status: 'open',
        applications: [],
        createdAt: '2024-11-01T00:00:00Z',
      },
    ],
    requiredSkills: ['React', 'Node.js', 'Sustainability', 'Product Design'],
    preferredExperience: ['Climate Tech', 'SaaS', 'Mobile Apps'],
    commitmentLevel: 'full-time',
    equityOffered: '5-10%',
    projectSpaceId: 'space1',
    chatEnabled: true,
    status: 'recruiting',
    visibility: 'public',
    featured: true,
    viewsCount: 342,
    applicationsCount: 18,
    likesCount: 45,
    spotlightEligible: true,
    tags: ['sustainability', 'climate-tech', 'saas', 'mobile'],
    location: 'Singapore',
    remoteWork: 'hybrid',
    savedBy: [],
    likedBy: [],
    sharedCount: 0,
    companyId: 'company1',
    postedJobs: ['job1', 'job2'],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: '2',
    name: 'LearnFlow',
    slug: 'learnflow',
    description: 'AI-powered personalized learning platform that adapts to each student\'s learning style and pace.',
    projectGoals: 'Build MVP with core AI features, launch beta with 5 schools, and raise seed funding.',
    industry: 'EdTech',
    stage: 'idea',
    founderId: 'user3',
    founderName: 'Michael Tan',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    members: [
      {
        id: 'tm3',
        startupId: '2',
        userId: 'user3',
        name: 'Michael Tan',
        role: 'Founder',
        title: 'CEO & Founder',
        bio: 'Former teacher turned entrepreneur, passionate about education technology',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
        isFounder: true,
        createdAt: '2024-10-01T00:00:00Z',
      },
    ],
    openPositions: [
      {
        id: 'pos3',
        teamCardId: '2',
        title: 'AI/ML Engineer',
        role: 'Engineer',
        description: 'Build the core AI recommendation engine and learning algorithms.',
        requiredSkills: ['Python', 'Machine Learning', 'TensorFlow', 'NLP'],
        experienceLevel: 'senior',
        commitment: 'full-time',
        equityOffered: '5-8%',
        status: 'open',
        applications: [],
        createdAt: '2024-11-01T00:00:00Z',
      },
      {
        id: 'pos4',
        teamCardId: '2',
        title: 'Product Manager',
        role: 'Product',
        description: 'Lead product strategy and work closely with engineering and design teams.',
        requiredSkills: ['Product Strategy', 'Agile', 'User Research', 'Roadmapping'],
        experienceLevel: 'mid',
        commitment: 'full-time',
        equityOffered: '3-5%',
        status: 'open',
        applications: [],
        createdAt: '2024-11-01T00:00:00Z',
      },
    ],
    requiredSkills: ['AI/ML', 'Python', 'React', 'Product Management'],
    preferredExperience: ['EdTech', 'AI/ML', 'SaaS'],
    commitmentLevel: 'full-time',
    equityOffered: '10-15%',
    projectSpaceId: 'space2',
    chatEnabled: true,
    status: 'recruiting',
    visibility: 'public',
    featured: false,
    viewsCount: 189,
    applicationsCount: 12,
    likesCount: 28,
    spotlightEligible: false,
    tags: ['edtech', 'ai', 'education', 'machine-learning'],
    location: 'Remote',
    remoteWork: 'remote',
    savedBy: [],
    likedBy: [],
    sharedCount: 0,
    companyId: 'company2',
    postedJobs: ['job3'],
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2024-11-18T00:00:00Z',
  },
  {
    id: '3',
    name: 'HealthSync',
    slug: 'healthsync',
    description: 'Unified healthcare data platform connecting patients, doctors, and hospitals for seamless medical record sharing.',
    projectGoals: 'Complete MVP, obtain healthcare compliance certifications, and partner with 3 major hospitals.',
    industry: 'HealthTech',
    stage: 'early',
    founderId: 'user4',
    founderName: 'Dr. Priya Sharma',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    members: [
      {
        id: 'tm4',
        startupId: '3',
        userId: 'user4',
        name: 'Dr. Priya Sharma',
        role: 'Founder',
        title: 'CEO & Co-Founder',
        bio: 'Medical doctor with 10 years experience, now building healthcare tech solutions',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
        isFounder: true,
        createdAt: '2024-09-01T00:00:00Z',
      },
      {
        id: 'tm5',
        startupId: '3',
        userId: 'user5',
        name: 'David Lee',
        role: 'Technical Lead',
        title: 'CTO',
        bio: 'Security expert specializing in healthcare data systems',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
        isFounder: false,
        createdAt: '2024-09-15T00:00:00Z',
      },
    ],
    openPositions: [
      {
        id: 'pos5',
        teamCardId: '3',
        title: 'Compliance Specialist',
        role: 'Compliance',
        description: 'Ensure our platform meets all healthcare regulations and data privacy requirements.',
        requiredSkills: ['HIPAA', 'Healthcare Compliance', 'Data Privacy', 'Regulatory Affairs'],
        experienceLevel: 'senior',
        commitment: 'part-time',
        equityOffered: '1-2%',
        status: 'open',
        applications: [],
        createdAt: '2024-11-01T00:00:00Z',
      },
    ],
    requiredSkills: ['Healthcare', 'Security', 'Compliance', 'Backend Development'],
    preferredExperience: ['HealthTech', 'Security', 'Compliance'],
    commitmentLevel: 'full-time',
    equityOffered: '3-7%',
    projectSpaceId: 'space3',
    chatEnabled: true,
    status: 'recruiting',
    visibility: 'public',
    featured: false,
    viewsCount: 256,
    applicationsCount: 8,
    likesCount: 32,
    spotlightEligible: false,
    tags: ['healthtech', 'healthcare', 'data-privacy', 'compliance'],
    location: 'Singapore',
    remoteWork: 'hybrid',
    savedBy: [],
    likedBy: [],
    sharedCount: 0,
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2024-11-19T00:00:00Z',
  },
  {
    id: '4',
    name: 'FoodieConnect',
    slug: 'foodieconnect',
    description: 'Social platform connecting food enthusiasts with local restaurants, chefs, and culinary experiences.',
    projectGoals: 'Launch in 3 cities, onboard 500 restaurants, and reach 10,000 active users.',
    industry: 'Food & Beverage',
    stage: 'idea',
    founderId: 'user6',
    founderName: 'Emma Wong',
    founderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    members: [
      {
        id: 'tm6',
        startupId: '4',
        userId: 'user6',
        name: 'Emma Wong',
        role: 'Founder',
        title: 'CEO & Founder',
        bio: 'Food blogger and entrepreneur passionate about connecting people through food',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
        isFounder: true,
        createdAt: '2024-11-01T00:00:00Z',
      },
    ],
    openPositions: [
      {
        id: 'pos6',
        teamCardId: '4',
        title: 'Full-Stack Developer',
        role: 'Engineer',
        description: 'Build the core platform with real-time features and mobile app.',
        requiredSkills: ['React', 'Node.js', 'PostgreSQL', 'Mobile Development'],
        experienceLevel: 'mid',
        commitment: 'full-time',
        equityOffered: '5-10%',
        status: 'open',
        applications: [],
        createdAt: '2024-11-01T00:00:00Z',
      },
      {
        id: 'pos7',
        teamCardId: '4',
        title: 'Community Manager',
        role: 'Community',
        description: 'Build and engage our community of food lovers and restaurant partners.',
        requiredSkills: ['Community Management', 'Social Media', 'Content Creation', 'Event Planning'],
        experienceLevel: 'entry',
        commitment: 'part-time',
        equityOffered: '1-2%',
        status: 'open',
        applications: [],
        createdAt: '2024-11-01T00:00:00Z',
      },
    ],
    requiredSkills: ['React', 'Node.js', 'Community Building', 'Marketing'],
    preferredExperience: ['Food & Beverage', 'Social Platforms', 'Marketplace'],
    commitmentLevel: 'flexible',
    equityOffered: '8-12%',
    projectSpaceId: 'space4',
    chatEnabled: true,
    status: 'recruiting',
    visibility: 'public',
    featured: false,
    viewsCount: 124,
    applicationsCount: 5,
    likesCount: 19,
    spotlightEligible: false,
    tags: ['food', 'social', 'marketplace', 'mobile'],
    location: 'Singapore',
    remoteWork: 'hybrid',
    savedBy: [],
    likedBy: [],
    sharedCount: 0,
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
];

