import { ProjectSpace, ChatMessage, ProjectTask, ProjectFile } from '@/types/platform';

// Mock Project Spaces for development
export const mockProjectSpaces: Record<string, ProjectSpace> = {
  space1: {
    id: 'space1',
    teamCardId: '1',
    name: 'EcoTrack Project Space',
    description: 'Collaboration workspace for EcoTrack team',
    chatMessages: [
      {
        id: 'msg1',
        projectSpaceId: 'space1',
        userId: 'user1',
        userName: 'Sarah Chen',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        content: 'Welcome everyone! Let\'s start by setting up our project goals and timeline.',
        createdAt: '2024-11-20T10:00:00Z',
      },
      {
        id: 'msg2',
        projectSpaceId: 'space1',
        userId: 'user2',
        userName: 'Alex Kumar',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        content: 'Great! I\'ve set up the initial project structure. We can start with the MVP features.',
        createdAt: '2024-11-20T10:15:00Z',
      },
    ],
    tasks: [
      {
        id: 'task1',
        projectSpaceId: 'space1',
        title: 'Design user dashboard',
        description: 'Create wireframes and mockups for the main dashboard',
        assignedTo: 'user2',
        assignedToName: 'Alex Kumar',
        status: 'in-progress',
        priority: 'high',
        dueDate: '2024-11-25T00:00:00Z',
        createdAt: '2024-11-20T09:00:00Z',
        updatedAt: '2024-11-20T10:00:00Z',
      },
      {
        id: 'task2',
        projectSpaceId: 'space1',
        title: 'Set up backend API',
        description: 'Create REST API endpoints for carbon tracking',
        assignedTo: 'user2',
        assignedToName: 'Alex Kumar',
        status: 'todo',
        priority: 'high',
        dueDate: '2024-11-28T00:00:00Z',
        createdAt: '2024-11-20T09:00:00Z',
        updatedAt: '2024-11-20T09:00:00Z',
      },
      {
        id: 'task3',
        projectSpaceId: 'space1',
        title: 'Research carbon calculation methods',
        description: 'Study existing methods for calculating carbon footprint',
        status: 'done',
        priority: 'medium',
        createdAt: '2024-11-19T09:00:00Z',
        updatedAt: '2024-11-20T08:00:00Z',
      },
    ],
    files: [
      {
        id: 'file1',
        projectSpaceId: 'space1',
        name: 'Project_Proposal.pdf',
        url: '#',
        type: 'application/pdf',
        size: 245678,
        uploadedBy: 'user1',
        uploadedByName: 'Sarah Chen',
        createdAt: '2024-11-15T10:00:00Z',
      },
      {
        id: 'file2',
        projectSpaceId: 'space1',
        name: 'Wireframes_v1.fig',
        url: '#',
        type: 'application/fig',
        size: 1234567,
        uploadedBy: 'user2',
        uploadedByName: 'Alex Kumar',
        createdAt: '2024-11-18T14:00:00Z',
      },
    ],
    milestones: [
      {
        id: 'milestone1',
        startupId: '1',
        title: 'MVP Launch',
        description: 'Launch the first version of EcoTrack with core features',
        date: '2024-12-15T00:00:00Z',
        category: 'product' as const,
        createdAt: '2024-11-01T00:00:00Z',
      },
      {
        id: 'milestone2',
        startupId: '1',
        title: 'Beta Testing',
        description: 'Complete beta testing with 100 users',
        date: '2024-12-01T00:00:00Z',
        category: 'growth' as const,
        createdAt: '2024-11-01T00:00:00Z',
      },
    ],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-11-20T10:15:00Z',
  },
  space2: {
    id: 'space2',
    teamCardId: '2',
    name: 'LearnFlow Project Space',
    description: 'Collaboration workspace for LearnFlow team',
    chatMessages: [
      {
        id: 'msg3',
        projectSpaceId: 'space2',
        userId: 'user3',
        userName: 'Michael Tan',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
        content: 'Let\'s discuss the AI recommendation engine architecture.',
        createdAt: '2024-11-19T15:00:00Z',
      },
    ],
    tasks: [
      {
        id: 'task4',
        projectSpaceId: 'space2',
        title: 'Research ML algorithms',
        description: 'Study different ML approaches for personalized learning',
        status: 'in-progress',
        priority: 'high',
        createdAt: '2024-11-18T09:00:00Z',
        updatedAt: '2024-11-19T10:00:00Z',
      },
    ],
    files: [],
    milestones: [
      {
        id: 'milestone3',
        startupId: '2',
        title: 'MVP Development',
        description: 'Complete MVP with core AI features',
        date: '2025-01-15T00:00:00Z',
        category: 'product' as const,
        createdAt: '2024-10-01T00:00:00Z',
      },
    ],
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2024-11-19T15:00:00Z',
  },
};

