import { CoFounderProfile } from '@/types/cofounder';

export const mockCofounderProfiles: CoFounderProfile[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    location: 'Singapore, Singapore',
    timezone: 'SGT',
    languages: ['English', 'Mandarin'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Artificial Intelligence', 'Financial/Fintech'],
    skills: ['Product Management', 'Strategy', 'Business Development', 'Machine Learning'],
    interests: ['AI', 'Blockchain', 'Fintech'],
    values: ['Innovation', 'Impact', 'Growth'],
    goals: ['Build scalable product', 'Raise Series A', 'Achieve product-market fit'],
    fundingStage: 'mvp',
    teamSize: '2-3',
    commitment: 'high',
    riskTolerance: 'high',
    workStyle: 'leadership',
    communication: 'direct',
    bio: 'Experienced product leader with 10+ years in AI and fintech. Built 2 successful startups from idea to Series A. Passionate about using technology to solve real-world problems.',
    lookingFor: 'Technical co-founder with ML expertise and startup experience',
    achievements: ['Built AI product with 1M+ users', 'Raised $5M Series A', 'Ex-Google Product Manager'],
    education: 'Stanford CS, MBA',
    previousStartups: 2,
    network: [],
    technicalStatus: false,
    cofounderStatus: false,
    responsibilityAreas: ['Product', 'Strategy', 'Sales & Marketing'],
    preferences: {
      ageRange: [25, 45],
      experienceLevel: ['intermediate', 'expert'],
      location: ['Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Machine Learning', 'Engineering'],
      values: ['Innovation', 'Impact'],
    },
    compatibilityScores: {},
    lastActive: new Date(),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Michael Tan',
    email: 'michael@example.com',
    location: 'Singapore, Singapore',
    timezone: 'SGT',
    languages: ['English', 'Mandarin', 'Malay'],
    experience: 'intermediate',
    availability: 'full-time',
    industry: ['Artificial Intelligence', 'Healthcare', 'B2B/Enterprise'],
    skills: ['Machine Learning', 'Python', 'TensorFlow', 'Deep Learning', 'Data Science'],
    interests: ['AI', 'Healthcare', 'Medical Technology'],
    values: ['Innovation', 'Quality', 'Impact'],
    goals: ['Build AI product', 'Make healthcare accessible', 'Improve patient outcomes'],
    fundingStage: 'prototype',
    teamSize: 'solo',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'collaborative',
    communication: 'analytical',
    bio: 'ML engineer passionate about healthcare AI. 5 years experience building ML systems. Published research in medical AI. Looking to build a startup that makes healthcare more accessible.',
    lookingFor: 'Business co-founder with healthcare domain expertise and go-to-market experience',
    achievements: ['Published ML research papers in top journals', 'Built healthcare AI prototype with 10K+ users', 'NUS Computer Science Graduate'],
    education: 'NUS Computer Science, PhD in ML',
    previousStartups: 0,
    network: [],
    technicalStatus: true,
    cofounderStatus: false,
    responsibilityAreas: ['Engineering', 'Product'],
    preferences: {
      ageRange: [25, 40],
      experienceLevel: ['intermediate', 'expert'],
      location: ['Singapore'],
      availability: ['full-time'],
      skills: ['Product Management', 'Business Development'],
      values: ['Innovation', 'Impact'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 3600000),
    isVerified: true,
    isPremium: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    location: 'Bangalore, India',
    timezone: 'IST',
    languages: ['English', 'Hindi', 'Kannada'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['E-Commerce', 'Marketplace', 'Consumer'],
    skills: ['Product Management', 'Operations', 'Supply Chain', 'Business Strategy'],
    interests: ['E-commerce', 'Marketplace', 'Consumer Tech'],
    values: ['Innovation', 'Customer Focus', 'Growth'],
    goals: ['Build marketplace platform', 'Scale to 1M+ users', 'Expand to Southeast Asia'],
    fundingStage: 'traction',
    teamSize: '4-5',
    commitment: 'high',
    riskTolerance: 'high',
    workStyle: 'leadership',
    communication: 'direct',
    bio: 'Serial entrepreneur with 12+ years in e-commerce. Built and sold 2 marketplace startups. Expert in operations, supply chain, and scaling consumer businesses.',
    lookingFor: 'Technical co-founder with marketplace/platform experience',
    achievements: ['Built marketplace with $10M+ GMV', 'Ex-Flipkart VP', 'Sold previous startup for $50M'],
    education: 'IIM Bangalore, Engineering',
    previousStartups: 2,
    network: [],
    technicalStatus: false,
    cofounderStatus: true,
    responsibilityAreas: ['Product', 'Operations', 'Strategy'],
    preferences: {
      ageRange: [28, 50],
      experienceLevel: ['expert'],
      location: ['India', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Engineering', 'Platform Development'],
      values: ['Innovation', 'Growth'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 7200000),
    isVerified: true,
    isPremium: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david@example.com',
    location: 'Seoul, South Korea',
    timezone: 'KST',
    languages: ['English', 'Korean'],
    experience: 'intermediate',
    availability: 'full-time',
    industry: ['Gaming', 'Entertainment', 'Augmented Reality/Virtual Reality'],
    skills: ['Game Development', 'Unity', 'C#', '3D Graphics', 'Game Design'],
    interests: ['Gaming', 'VR/AR', 'Entertainment'],
    values: ['Innovation', 'Creativity', 'Quality'],
    goals: ['Build successful game studio', 'Launch hit mobile game', 'Expand to global markets'],
    fundingStage: 'prototype',
    teamSize: 'solo',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'collaborative',
    communication: 'creative',
    bio: 'Game developer with 6 years experience. Worked on 3 published mobile games. Passionate about creating engaging gaming experiences. Looking to build the next big mobile game.',
    lookingFor: 'Business/marketing co-founder with gaming industry connections',
    achievements: ['Published 3 mobile games with 500K+ downloads', 'Ex-Nexon Game Developer', 'Award-winning game designer'],
    education: 'KAIST Computer Science',
    previousStartups: 0,
    network: [],
    technicalStatus: true,
    cofounderStatus: false,
    responsibilityAreas: ['Engineering', 'Design'],
    preferences: {
      ageRange: [25, 40],
      experienceLevel: ['intermediate', 'expert'],
      location: ['South Korea', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Marketing', 'Business Development'],
      values: ['Innovation', 'Creativity'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 1800000),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Emma Wilson',
    email: 'emma@example.com',
    location: 'London, UK',
    timezone: 'GMT',
    languages: ['English', 'French'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Education/Edtech', 'B2B/Enterprise', 'SaaS'],
    skills: ['Product Management', 'Sales & Marketing', 'Customer Success', 'Strategy'],
    interests: ['Edtech', 'SaaS', 'Enterprise Software'],
    values: ['Impact', 'Quality', 'Customer Focus'],
    goals: ['Build B2B SaaS platform', 'Achieve $10M ARR', 'Help transform education'],
    fundingStage: 'mvp',
    teamSize: '2-3',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'leadership',
    communication: 'diplomatic',
    bio: 'Product leader with 10+ years in B2B SaaS and edtech. Built products used by 100K+ users. Expert in go-to-market strategy and customer success.',
    lookingFor: 'Technical co-founder with SaaS/enterprise experience',
    achievements: ['Built SaaS product with $5M ARR', 'Ex-Salesforce Product Manager', 'Helped 50K+ students'],
    education: 'Oxford University, MBA',
    previousStartups: 1,
    network: [],
    technicalStatus: false,
    cofounderStatus: false,
    responsibilityAreas: ['Product', 'Sales & Marketing', 'Customer Success'],
    preferences: {
      ageRange: [28, 45],
      experienceLevel: ['intermediate', 'expert'],
      location: ['UK', 'Remote'],
      availability: ['full-time'],
      skills: ['Engineering', 'SaaS Development'],
      values: ['Impact', 'Quality'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 5400000),
    isVerified: true,
    isPremium: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Raj Patel',
    email: 'raj@example.com',
    location: 'Mumbai, India',
    timezone: 'IST',
    languages: ['English', 'Hindi', 'Gujarati'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Financial/Fintech', 'Blockchain', 'B2B/Enterprise'],
    skills: ['Blockchain', 'Smart Contracts', 'Solidity', 'DeFi', 'Cryptocurrency'],
    interests: ['Blockchain', 'DeFi', 'Fintech'],
    values: ['Innovation', 'Transparency', 'Impact'],
    goals: ['Build DeFi platform', 'Raise funding', 'Disrupt traditional finance'],
    fundingStage: 'prototype',
    teamSize: '2-3',
    commitment: 'high',
    riskTolerance: 'high',
    workStyle: 'leadership',
    communication: 'analytical',
    bio: 'Blockchain engineer and DeFi expert with 8 years experience. Built multiple DeFi protocols. Deep understanding of smart contracts and blockchain infrastructure.',
    lookingFor: 'Business co-founder with fintech/regulatory expertise',
    achievements: ['Built DeFi protocol with $100M+ TVL', 'Ex-ConsenSys Engineer', 'Published blockchain research'],
    education: 'IIT Bombay, Computer Science',
    previousStartups: 1,
    network: [],
    technicalStatus: true,
    cofounderStatus: true,
    responsibilityAreas: ['Engineering', 'Product'],
    preferences: {
      ageRange: [25, 45],
      experienceLevel: ['intermediate', 'expert'],
      location: ['India', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Business Development', 'Regulatory Compliance'],
      values: ['Innovation', 'Transparency'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 900000),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Lisa Zhang',
    email: 'lisa@example.com',
    location: 'Shanghai, China',
    timezone: 'CST',
    languages: ['English', 'Mandarin'],
    experience: 'intermediate',
    availability: 'full-time',
    industry: ['E-Commerce', 'Consumer', 'Marketplace'],
    skills: ['UI/UX Design', 'Product Design', 'User Research', 'Design Systems'],
    interests: ['E-commerce', 'Consumer Products', 'Design'],
    values: ['Quality', 'User Experience', 'Innovation'],
    goals: ['Build beautiful consumer product', 'Create exceptional user experience', 'Scale to millions'],
    fundingStage: 'idea',
    teamSize: 'solo',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'collaborative',
    communication: 'creative',
    bio: 'Product designer with 7 years experience. Designed products for Alibaba, Tencent. Passionate about creating beautiful, user-friendly experiences.',
    lookingFor: 'Technical and business co-founders to build e-commerce startup',
    achievements: ['Designed products with 10M+ users', 'Ex-Alibaba Senior Designer', 'Award-winning UX designer'],
    education: 'Tsinghua University, Design',
    previousStartups: 0,
    network: [],
    technicalStatus: false,
    cofounderStatus: false,
    responsibilityAreas: ['Design', 'Product'],
    preferences: {
      ageRange: [25, 40],
      experienceLevel: ['intermediate', 'expert'],
      location: ['China', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Engineering', 'Business Development'],
      values: ['Quality', 'User Experience'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 3600000),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'James Anderson',
    email: 'james@example.com',
    location: 'Sydney, Australia',
    timezone: 'AEST',
    languages: ['English'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Climate/Sustainability', 'Energy', 'Hard Tech'],
    skills: ['Engineering', 'Hardware', 'Renewable Energy', 'Product Development'],
    interests: ['Climate Tech', 'Renewable Energy', 'Sustainability'],
    values: ['Sustainability', 'Impact', 'Innovation'],
    goals: ['Build climate tech solution', 'Reduce carbon emissions', 'Scale globally'],
    fundingStage: 'mvp',
    teamSize: '2-3',
    commitment: 'high',
    riskTolerance: 'high',
    workStyle: 'leadership',
    communication: 'direct',
    bio: 'Engineer and climate tech entrepreneur with 12 years experience. Built hardware solutions for renewable energy. Passionate about fighting climate change.',
    lookingFor: 'Business co-founder with climate tech/government relations experience',
    achievements: ['Built renewable energy hardware', 'Raised $3M seed round', 'Ex-Tesla Engineer'],
    education: 'University of Sydney, Engineering',
    previousStartups: 1,
    network: [],
    technicalStatus: true,
    cofounderStatus: false,
    responsibilityAreas: ['Engineering', 'Product'],
    preferences: {
      ageRange: [30, 50],
      experienceLevel: ['expert'],
      location: ['Australia', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Business Development', 'Government Relations'],
      values: ['Sustainability', 'Impact'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 7200000),
    isVerified: true,
    isPremium: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: 'Maria Garcia',
    email: 'maria@example.com',
    location: 'Barcelona, Spain',
    timezone: 'CET',
    languages: ['English', 'Spanish', 'Catalan'],
    experience: 'intermediate',
    availability: 'part-time',
    industry: ['Health/Wellness', 'Consumer', 'Marketplace'],
    skills: ['Marketing', 'Content Creation', 'Social Media', 'Brand Strategy'],
    interests: ['Health & Wellness', 'Consumer Products', 'Lifestyle'],
    values: ['Wellness', 'Quality', 'Customer Focus'],
    goals: ['Build wellness platform', 'Help people live healthier', 'Create community'],
    fundingStage: 'idea',
    teamSize: 'solo',
    commitment: 'medium',
    riskTolerance: 'low',
    workStyle: 'collaborative',
    communication: 'diplomatic',
    bio: 'Marketing expert with 6 years in health and wellness. Built brands from scratch. Passionate about helping people live healthier, happier lives.',
    lookingFor: 'Technical and product co-founders for wellness startup',
    achievements: ['Built wellness brand with 100K+ followers', 'Ex-Lululemon Marketing Manager', 'Award-winning marketer'],
    education: 'IESE Business School, Marketing',
    previousStartups: 0,
    network: [],
    technicalStatus: false,
    cofounderStatus: false,
    responsibilityAreas: ['Sales & Marketing', 'Customer Success'],
    preferences: {
      ageRange: [25, 40],
      experienceLevel: ['intermediate', 'expert'],
      location: ['Spain', 'Remote'],
      availability: ['full-time', 'part-time'],
      skills: ['Engineering', 'Product Management'],
      values: ['Wellness', 'Quality'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 10800000),
    isVerified: false,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: 'Kenji Yamamoto',
    email: 'kenji@example.com',
    location: 'Tokyo, Japan',
    timezone: 'JST',
    languages: ['English', 'Japanese'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Robotics', 'Hardware', 'Hard Tech'],
    skills: ['Robotics', 'AI', 'Hardware Engineering', 'Computer Vision'],
    interests: ['Robotics', 'AI', 'Hardware'],
    values: ['Innovation', 'Quality', 'Excellence'],
    goals: ['Build robotics startup', 'Create innovative robots', 'Scale globally'],
    fundingStage: 'prototype',
    teamSize: '2-3',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'collaborative',
    communication: 'analytical',
    bio: 'Robotics engineer with 10 years experience. Worked at leading robotics companies. Expert in AI, computer vision, and hardware integration.',
    lookingFor: 'Business co-founder with robotics/industrial experience',
    achievements: ['Built industrial robots', 'Ex-Fanuc Engineer', 'Published robotics research'],
    education: 'University of Tokyo, Robotics',
    previousStartups: 0,
    network: [],
    technicalStatus: true,
    cofounderStatus: true,
    responsibilityAreas: ['Engineering', 'Product'],
    preferences: {
      ageRange: [28, 45],
      experienceLevel: ['intermediate', 'expert'],
      location: ['Japan', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Business Development', 'Industrial Sales'],
      values: ['Innovation', 'Quality'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 1800000),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    name: 'Sophie Martin',
    email: 'sophie@example.com',
    location: 'Paris, France',
    timezone: 'CET',
    languages: ['English', 'French', 'Spanish'],
    experience: 'intermediate',
    availability: 'full-time',
    industry: ['Travel/Tourism', 'Marketplace', 'Consumer'],
    skills: ['Product Management', 'Operations', 'Customer Experience', 'Strategy'],
    interests: ['Travel', 'Tourism', 'Hospitality'],
    values: ['Customer Experience', 'Quality', 'Innovation'],
    goals: ['Build travel platform', 'Improve travel experience', 'Scale to global markets'],
    fundingStage: 'idea',
    teamSize: 'solo',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'leadership',
    communication: 'diplomatic',
    bio: 'Product manager with 7 years in travel and hospitality. Worked at Booking.com and Airbnb. Passionate about making travel more accessible and enjoyable.',
    lookingFor: 'Technical co-founder with marketplace/platform experience',
    achievements: ['Launched travel features with 1M+ users', 'Ex-Airbnb Product Manager', 'Improved booking conversion by 30%'],
    education: 'HEC Paris, Business',
    previousStartups: 0,
    network: [],
    technicalStatus: false,
    cofounderStatus: false,
    responsibilityAreas: ['Product', 'Operations', 'Customer Success'],
    preferences: {
      ageRange: [25, 40],
      experienceLevel: ['intermediate', 'expert'],
      location: ['France', 'Remote'],
      availability: ['full-time'],
      skills: ['Engineering', 'Platform Development'],
      values: ['Customer Experience', 'Quality'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 5400000),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '12',
    name: 'Amit Kumar',
    email: 'amit@example.com',
    location: 'Delhi, India',
    timezone: 'IST',
    languages: ['English', 'Hindi'],
    experience: 'beginner',
    availability: 'full-time',
    industry: ['Education/Edtech', 'B2B/Enterprise', 'SaaS'],
    skills: ['Full Stack Development', 'React', 'Node.js', 'MongoDB', 'AWS'],
    interests: ['Edtech', 'SaaS', 'Education'],
    values: ['Impact', 'Innovation', 'Growth'],
    goals: ['Build edtech platform', 'Help students learn better', 'Scale to 1M+ users'],
    fundingStage: 'prototype',
    teamSize: 'solo',
    commitment: 'high',
    riskTolerance: 'high',
    workStyle: 'collaborative',
    communication: 'analytical',
    bio: 'Full-stack developer with 3 years experience. Built multiple web applications. Passionate about using technology to improve education.',
    lookingFor: 'Business and product co-founders for edtech startup',
    achievements: ['Built learning platform with 10K+ users', 'IIT Graduate', 'Open source contributor'],
    education: 'IIT Delhi, Computer Science',
    previousStartups: 0,
    network: [],
    technicalStatus: true,
    cofounderStatus: false,
    responsibilityAreas: ['Engineering'],
    preferences: {
      ageRange: [22, 35],
      experienceLevel: ['intermediate', 'expert'],
      location: ['India', 'Remote'],
      availability: ['full-time'],
      skills: ['Product Management', 'Business Development'],
      values: ['Impact', 'Innovation'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 3600000),
    isVerified: false,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '13',
    name: 'Yuki Tanaka',
    email: 'yuki@example.com',
    location: 'Tokyo, Japan',
    timezone: 'JST',
    languages: ['English', 'Japanese'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Biomedical/Biotech', 'Healthcare', 'Hard Tech'],
    skills: ['Biotechnology', 'Research', 'Product Development', 'Regulatory Affairs'],
    interests: ['Biotech', 'Healthcare', 'Medical Research'],
    values: ['Impact', 'Quality', 'Innovation'],
    goals: ['Build biotech startup', 'Develop life-saving treatments', 'Get FDA approval'],
    fundingStage: 'prototype',
    teamSize: '2-3',
    commitment: 'high',
    riskTolerance: 'high',
    workStyle: 'leadership',
    communication: 'analytical',
    bio: 'Biotech researcher with 15 years experience. PhD in Biotechnology. Worked on multiple drug development projects. Expert in regulatory affairs.',
    lookingFor: 'Business co-founder with biotech/pharma industry experience',
    achievements: ['Published 20+ research papers', 'Ex-Pfizer Researcher', 'Led drug development projects'],
    education: 'University of Tokyo, PhD Biotechnology',
    previousStartups: 0,
    network: [],
    technicalStatus: true,
    cofounderStatus: true,
    responsibilityAreas: ['Product', 'Strategy'],
    preferences: {
      ageRange: [30, 50],
      experienceLevel: ['expert'],
      location: ['Japan', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Business Development', 'Regulatory Affairs'],
      values: ['Impact', 'Quality'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 7200000),
    isVerified: true,
    isPremium: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '14',
    name: 'Alex Thompson',
    email: 'alex@example.com',
    location: 'San Francisco, USA',
    timezone: 'PST',
    languages: ['English'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Developer Tools', 'B2B/Enterprise', 'SaaS'],
    skills: ['Backend Engineering', 'Infrastructure', 'DevOps', 'System Design'],
    interests: ['Developer Tools', 'Infrastructure', 'SaaS'],
    values: ['Innovation', 'Quality', 'Developer Experience'],
    goals: ['Build developer tools platform', 'Help developers be more productive', 'Scale to enterprise'],
    fundingStage: 'mvp',
    teamSize: '2-3',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'collaborative',
    communication: 'direct',
    bio: 'Backend engineer with 12 years experience. Built infrastructure at scale. Ex-Google, Ex-Stripe. Expert in distributed systems and developer tools.',
    lookingFor: 'Product and business co-founders for developer tools startup',
    achievements: ['Built infrastructure serving 1B+ requests/day', 'Ex-Google Engineer', 'Open source maintainer'],
    education: 'Stanford, Computer Science',
    previousStartups: 1,
    network: [],
    technicalStatus: true,
    cofounderStatus: false,
    responsibilityAreas: ['Engineering'],
    preferences: {
      ageRange: [28, 45],
      experienceLevel: ['intermediate', 'expert'],
      location: ['USA', 'Remote'],
      availability: ['full-time'],
      skills: ['Product Management', 'Business Development'],
      values: ['Innovation', 'Quality'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 1800000),
    isVerified: true,
    isPremium: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '15',
    name: 'Nina Singh',
    email: 'nina@example.com',
    location: 'Singapore, Singapore',
    timezone: 'SGT',
    languages: ['English', 'Hindi', 'Mandarin'],
    experience: 'intermediate',
    availability: 'full-time',
    industry: ['Real Estate/Proptech', 'B2B/Enterprise', 'Marketplace'],
    skills: ['Product Management', 'Sales & Marketing', 'Real Estate', 'Operations'],
    interests: ['Proptech', 'Real Estate', 'Marketplace'],
    values: ['Innovation', 'Customer Focus', 'Growth'],
    goals: ['Build proptech platform', 'Transform real estate industry', 'Scale to Southeast Asia'],
    fundingStage: 'idea',
    teamSize: 'solo',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'leadership',
    communication: 'diplomatic',
    bio: 'Product manager with 6 years in real estate and proptech. Worked at leading property platforms. Passionate about using technology to improve real estate transactions.',
    lookingFor: 'Technical and business co-founders for proptech startup',
    achievements: ['Launched property features with 500K+ users', 'Ex-PropertyGuru Product Manager', 'Improved conversion by 25%'],
    education: 'NUS Business, Real Estate',
    previousStartups: 0,
    network: [],
    technicalStatus: false,
    cofounderStatus: false,
    responsibilityAreas: ['Product', 'Sales & Marketing', 'Operations'],
    preferences: {
      ageRange: [25, 40],
      experienceLevel: ['intermediate', 'expert'],
      location: ['Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Engineering', 'Business Development'],
      values: ['Innovation', 'Customer Focus'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 900000),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '16',
    name: 'Carlos Rodriguez',
    email: 'carlos@example.com',
    location: 'São Paulo, Brazil',
    timezone: 'BRT',
    languages: ['English', 'Portuguese', 'Spanish'],
    experience: 'intermediate',
    availability: 'full-time',
    industry: ['Financial/Fintech', 'B2B/Enterprise', 'SaaS'],
    skills: ['Full Stack Development', 'Fintech', 'Payment Systems', 'API Development'],
    interests: ['Fintech', 'Payments', 'Banking'],
    values: ['Innovation', 'Security', 'Impact'],
    goals: ['Build fintech platform', 'Improve financial inclusion', 'Scale to Latin America'],
    fundingStage: 'prototype',
    teamSize: 'solo',
    commitment: 'high',
    riskTolerance: 'high',
    workStyle: 'collaborative',
    communication: 'analytical',
    bio: 'Full-stack developer with 7 years in fintech. Built payment systems and banking APIs. Passionate about financial inclusion and improving access to financial services.',
    lookingFor: 'Business and product co-founders for fintech startup',
    achievements: ['Built payment system processing $100M+', 'Ex-Nubank Engineer', 'Launched banking API'],
    education: 'USP, Computer Science',
    previousStartups: 0,
    network: [],
    technicalStatus: true,
    cofounderStatus: false,
    responsibilityAreas: ['Engineering', 'Product'],
    preferences: {
      ageRange: [25, 40],
      experienceLevel: ['intermediate', 'expert'],
      location: ['Brazil', 'Remote'],
      availability: ['full-time'],
      skills: ['Product Management', 'Business Development'],
      values: ['Innovation', 'Security'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 3600000),
    isVerified: true,
    isPremium: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '17',
    name: 'Hannah Lee',
    email: 'hannah@example.com',
    location: 'Seoul, South Korea',
    timezone: 'KST',
    languages: ['English', 'Korean'],
    experience: 'expert',
    availability: 'full-time',
    industry: ['Food/Beverage', 'Consumer', 'E-Commerce'],
    skills: ['Operations', 'Supply Chain', 'Food & Beverage', 'Business Strategy'],
    interests: ['Food Tech', 'Consumer Products', 'E-commerce'],
    values: ['Quality', 'Customer Focus', 'Innovation'],
    goals: ['Build food tech platform', 'Improve food delivery', 'Scale to Asia'],
    fundingStage: 'traction',
    teamSize: '4-5',
    commitment: 'high',
    riskTolerance: 'medium',
    workStyle: 'leadership',
    communication: 'direct',
    bio: 'Operations expert with 10 years in food and beverage. Built supply chains for food delivery platforms. Expert in logistics and operations.',
    lookingFor: 'Technical co-founder with food tech/platform experience',
    achievements: ['Built food delivery operations', 'Ex-Baemin Operations Director', 'Scaled to 1M+ orders/month'],
    education: 'Seoul National University, Business',
    previousStartups: 1,
    network: [],
    technicalStatus: false,
    cofounderStatus: true,
    responsibilityAreas: ['Operations', 'Strategy'],
    preferences: {
      ageRange: [28, 45],
      experienceLevel: ['intermediate', 'expert'],
      location: ['South Korea', 'Singapore', 'Remote'],
      availability: ['full-time'],
      skills: ['Engineering', 'Platform Development'],
      values: ['Quality', 'Customer Focus'],
    },
    compatibilityScores: {},
    lastActive: new Date(Date.now() - 5400000),
    isVerified: true,
    isPremium: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

